### ISSUE TITLE
[Meta] Satellite Consumer

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/Satip#74]
The tasks below are for making an app that collected live satellite data and saves them to directory.

- [x] main app: https://github.com/openclimatefix/Satip/issues/71
- [x] readme: https://github.com/openclimatefix/Satip/issues/70
- [x] tests: https://github.com/openclimatefix/Satip/issues/73
- [ ] codecov: #72 
- [ ] plot: #75 
- [x] lates folder: https://github.com/openclimatefix/Satip/issues/94

other repos
- [x] loading netcdf: https://github.com/openclimatefix/nowcasting_dataset/issues/606
- [x] terraform s3: https://github.com/openclimatefix/nowcasting_infrastructure/issues/36
- [x] terraform ecs: https://github.com/openclimatefix/nowcasting_infrastructure/issues/37
